name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    # 二重実行を防ぐ
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - id: tag-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          dry_run: true  # tagはRelease作成時つける

      - name: Login to GitHub Container Registry
        if: ${{ success() && steps.tag-version.outputs.release_type != false }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        if: ${{ success() && steps.tag-version.outputs.release_type != false }}
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/teruyamato0731/dev-humble
          imageTag: ${{ steps.tag-version.outputs.new_version }},latest
          cacheFrom: ghcr.io/teruyamato0731/dev-humble
          runCmd: echo $ROS_DISTRO

      - name: Create a GitHub release
        if: ${{ success() && steps.tag-version.outputs.release_type != false }}
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.ref_name }}
          tag: ${{ steps.tag-version.outputs.new_tag }}
          body: ${{ steps.tag-version.outputs.changelog }}
